{\rtf1\ansi\ansicpg1252\cocoartf2865
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Mega Auto Login\
\
on:\
  workflow_dispatch:  # Manual trigger from GitHub UI\
  schedule:\
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC\
\
jobs:\
  run-orchestration:\
    runs-on: ubuntu-latest\
\
    steps:\
      - name: Checkout repository\
        uses: actions/checkout@v3\
\
      - name: Set up Python\
        uses: actions/setup-python@v4\
        with:\
          python-version: '3.10'\
\
      - name: Install dependencies\
        run: |\
          pip install flask selenium\
\
      - name: Run orchestration\
        env:\
          LOGIN_USER: $\{\{ secrets.LOGIN_USER \}\}\
          LOGIN_PASS: $\{\{ secrets.LOGIN_PASS \}\}\
          CHROMEDRIVER_PATH: "/usr/bin/chromedriver"\
          LOGIN_FILE: "LOGS.txt"\
          FAILED_LOGINS_FILE: "failed_logins.txt"\
          RETRY_LOG_DIR: "retry_logs"\
        run: |\
          python mega_online_auto.py}
